import AppIcon from "../components/icons/AppIcon";

const cities = [
    "Tirana",
    "Durrësi",
    "Shkodra",
    "Elbasani",
    "Vlora",
    "Korça",
    "Fieri",
    "Berati",
    "Lushnja",
    "Pogradeci",
    "Kavaja",
    "Laçi",
    "Lezha",
    "Kukësi",
    "Gjirokastra",
    "Patosi",
    "Kruja",
    "Kuçova",
    "Saranda",
    "Peshkopia",
    "Burreli",
    "Cërriku",
    "Çorovoda",
    "Shijaku",
    "Librazhdi",
    "Tepelena",
    "Gramshi",
    "Poliçani",
    "Bulqiza",
    "Përmeti",
    "Fushë-Kruja",
    "Kamëza",
    "Rrësheni",
    "Ballshi",
    "Mamurrasi",
    "Bajram Curri",
    "Erseka",
    "Peqini",
    "Divjaka",
    "Selenica",
    "Bilishti",
    "Roskoveci",
    "Këlcyra",
    "Puka",
    "Memaliaj",
    "Rrogozhina",
    "Ura Vajgurore",
    "Himara",
    "Delvina",
    "Vora",
    "Kopliku",
    "Maliqi",
    "Përrenjasi",
    "Shtërmeni",
    "Kruma",
    "Libohova",
    "Orikumi",
    "Fushë-Arrëza",
    "Shëngjini",
    "Rubiku",
    "Miloti",
    "Leskoviku",
    "Konispoli",
    "Krasta",
    "Kërraba"
];
const citiesObject = [
    {"id":"1","name":"Tirana"},
    {"id":"2","name":"Durrësi"},
    {"id":"3","name":"Shkodra"},
    {"id":"4","name":"Elbasani"},
    {"id":"5","name":"Vlora"},
    {"id":"6","name":"Korça"},
    {"id":"7","name":"Fieri"},
    {"id":"8","name":"Berati"},
    {"id":"9","name":"Lushnja"},
    {"id":"10","name":"Pogradeci"},
    {"id":"11","name":"Kavaja"},
    {"id":"12","name":"Laçi"},
    {"id":"13","name":"Lezha"},
    {"id":"14","name":"Kukësi"},
    {"id":"15","name":"Gjirokastra"},
    {"id":"16","name":"Patosi"},
    {"id":"17","name":"Kruja"},
    {"id":"18","name":"Kuçova"},
    {"id":"19","name":"Saranda"},
    {"id":"20","name":"Peshkopia"},
    {"id":"21","name":"Burreli"},
    {"id":"22","name":"Cërriku"},
    {"id":"23","name":"Çorovoda"},
    {"id":"24","name":"Shijaku"},
    {"id":"25","name":"Librazhdi"},
    {"id":"26","name":"Tepelena"},
    {"id":"27","name":"Gramshi"},
    {"id":"28","name":"Poliçani"},
    {"id":"29","name":"Bulqiza"},
    {"id":"30","name":"Përmeti"},
    {"id":"31","name":"Fushë-Kruja"},
    {"id":"32","name":"Kamëza"},
    {"id":"33","name":"Rrësheni"},
    {"id":"34","name":"Ballshi"},
    {"id":"35","name":"Mamurrasi"},
    {"id":"36","name":"Bajram Curri"},
    {"id":"37","name":"Erseka"},
    {"id":"38","name":"Peqini"},
    {"id":"39","name":"Divjaka"},
    {"id":"40","name":"Selenica"},
    {"id":"41","name":"Bilishti"},
    {"id":"42","name":"Roskoveci"},
    {"id":"43","name":"Këlcyra"},
    {"id":"44","name":"Puka"},
    {"id":"45","name":"Memaliaj"},
    {"id":"46","name":"Rrogozhina"},
    {"id":"47","name":"Ura Vajgurore"},
    {"id":"48","name":"Himara"},
    {"id":"49","name":"Delvina"},
    {"id":"50","name":"Vora"},
    {"id":"51","name":"Kopliku"},
    {"id":"52","name":"Maliqi"},
    {"id":"53","name":"Përrenjasi"},
    {"id":"54","name":"Shtërmeni"},
    {"id":"55","name":"Kruma"},
    {"id":"56","name":"Libohova"},
    {"id":"57","name":"Orikumi"},
    {"id":"58","name":"Fushë-Arrëza"},
    {"id":"59","name":"Shëngjini"},
    {"id":"60","name":"Rubiku"},
    {"id":"61","name":"Miloti"},
    {"id":"62","name":"Leskoviku"},
    {"id":"63","name":"Konispoli"},
    {"id":"64","name":"Krasta"},
    {"id":"65","name":"Kërraba"}
];


const sports = [
    {
        id:1,
        name: 'Futboll',
        icon: 'football'
    },
    {
        id:2,
        name: 'Basketboll',
        icon: 'basketball'
    },
    {
        id:3,
        name: 'Volejboll',
        icon: 'voleyball'
    },
    {
        id:4,
        name: 'Tenis',
        icon: 'tenis'
    },

]

const StaticData = {
    cities,
    citiesObject,
    sports
}

export default StaticData;